# AI Portfolio Service - Base Configuration
# 공통 설정 (모든 환경에서 공유)

# =============================================================================
# Logging Configuration (Base)
# =============================================================================
logging:
  level: "INFO"
  format: "json"
  include_request_id: true

# =============================================================================
# RAG Configuration (Base)  
# =============================================================================
rag:
  chunk_size: 500
  chunk_overlap: 75
  top_k: 5
  similarity_threshold: 0.7
  max_context_length: 8000
  project_priority_boost: true
  include_metadata: true

# =============================================================================
# Performance Configuration (Base)
# =============================================================================
performance:
  max_concurrent_requests: 50
  request_timeout_seconds: 30
  db_connection_timeout: 10
  
  # 메트릭 수집 설정
  metrics:
    collection_interval: 60
    
  # 헬스체크 설정
  health_check:
    interval: 30
    timeout: 5