# AI-Service Configuration
api:
  title: "AI Portfolio Service"
  version: "2.0.0"
  description: "Complete AI service with backend logic migration"

# Database connection
database:
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600

# Question Analysis Settings
question_analysis:
  ai_keywords:
    - "프로젝트"
    - "경험" 
    - "기술"
    - "스킬"
    - "개발"
    - "경력"
  immediate_responses:
    greetings:
      - "안녕"
      - "안녕하세요"  
      - "hi"
      - "hello"
    contact:
      - "연락처"
      - "이메일"
      - "email"

# Context Building Settings  
context_builder:
  max_context_length: 8000
  project_priority_boost: true
  include_metadata: true
  
# LLM Generation Settings
generation:
  model: "gemini-pro"
  temperature: 0.3
  max_tokens: 1000
  system_prompt_template: |
    당신은 개발자 포트폴리오를 소개하는 전문적이고 친근한 AI 어시스턴트입니다.
    제공된 포트폴리오 정보를 바탕으로 정확하고 도움이 되는 답변을 해주세요.
    기술적인 내용은 구체적으로, 경험은 성과 중심으로 설명해주세요.

# Caching Settings
cache:
  redis_key_prefix: "ai_service:"
  default_ttl: 3600
  context_ttl: 7200
  
# Logging Settings  
logging:
  level: "INFO"
  format: "json"
  include_request_id: true

# Document Processing Settings
document_processing:
  source_directory: "docs/projects/"
  file_pattern: "*.md"
  encoding: "utf-8"
  enable_validation: true
  max_concurrent_processing: 5
  
  # Splitter Configuration
  splitter:
    chunk_size: 1000
    chunk_overlap: 200
    header_levels: [1, 2, 3]  # Split on H1, H2, H3
  
  # Validator Configuration
  validator:
    max_file_size_mb: 10
    min_chunk_size: 100
    max_chunk_size: 2000
    min_overlap_ratio: 0.1
    max_overlap_ratio: 0.3

# Performance Settings
performance:
  max_concurrent_requests: 50
  request_timeout_seconds: 30
  db_connection_timeout: 10