# LangChain 프레임워크 전용 프롬프트 설정
# LangChain 체인에서 사용되는 프롬프트 템플릿들을 정의

# 기본 텍스트 생성 프롬프트
basic_text_generation:
  system: "main_assistant"
  
  human_template: |
    {prompt}

# RAG 체인 프롬프트
rag_chain:
  system: "main_assistant"
  
  human_template: |
    질문: {question}

    컨텍스트:
    {context}

    위 컨텍스트를 바탕으로 질문에 답변해주세요.

# 요약 체인 프롬프트
summarization_chain:
  system: "summary_writer"
  
  human_template: |
    다음 텍스트를 요약해주세요:

    {text}

    요약:

# 한국어 쿼리 분석 프롬프트
korean_query_analysis:
  system: "question_classifier"
  
  human_template: |
    다음 한국어 질문을 분석하여 검색 전략을 결정해주세요:

    질문: {query}

    한국어 분석 기준:
    1. 질문 유형 분류 (프로젝트, 경험, 기술, 일반)
    2. 검색 전략 결정 (의미적, 키워드, 하이브리드, 특정)
    3. 필요한 컨텍스트 유형 식별
    4. 한국어 특성 고려 (조사, 어미 변화 등)

    분석 결과를 JSON으로 반환해주세요:
    {{"query_type": "분류된 질문 유형", "confidence": 0.0-1.0, "search_strategy": "검색 전략", "context_requirements": ["필요한 컨텍스트 목록"]}}

# 한국어 응답 생성 프롬프트
korean_response_generation:
  system: "main_assistant"
  
  human_template: |
    당신은 전문적인 AI 어시스턴트입니다. 주어진 컨텍스트를 바탕으로 사용자의 한국어 질문에 정확하고 도움이 되는 답변을 제공해주세요.

    질문 유형: {query_type}
    검색 전략: {search_strategy}

    컨텍스트:
    {context}

    질문: {query}

    한국어 답변 규칙:
    1. 컨텍스트에 기반한 정확한 정보만 제공하세요
    2. 자연스러운 한국어로 답변하세요
    3. 질문 유형에 맞는 적절한 톤으로 답변하세요
    4. 불확실한 정보는 명시하세요
    5. 구체적이고 실용적인 답변을 작성하세요

    답변:

# 사용자 정의 체인 기본 템플릿
custom_chain_template:
  system: "main_assistant"
  
  human_template: |
    {template}