[tool.ruff]
# Ruff 통합 설정 파일 - 모든 Python 품질 도구 통합
# See https://docs.astral.sh/ruff/configuration/

# Python 버전 설정
target-version = "py311"

# 린팅할 파일 패턴
include = ["*.py", "*.pyi"]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "venv",
    "tests/",
    "test_*.py",
    "*_test.py"
]

# 린터 설정 (flake8, isort, bandit 기능 통합)
lint.enable = [
    "E",   # pycodestyle errors
    "W",   # pycodestyle warnings
    "F",   # pyflakes
    "I",   # isort (import 정렬)
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
    "ARG", # flake8-unused-arguments
    "SIM", # flake8-simplify
    "TCH", # flake8-type-checking
    "Q",   # flake8-quotes
    "RUF", # Ruff-specific rules
    "S",   # bandit (보안 검사)
    "A",   # flake8-builtins
    "COM", # flake8-commas
    "DTZ", # flake8-datetimez
    "EM",  # flake8-errmsg
    "EXE", # flake8-executable
    "FA",  # flake8-future-annotations
    "ISC", # flake8-implicit-str-concat
    "ICN", # flake8-import-conventions
    "G",   # flake8-logging-format
    "INP", # flake8-no-pep420
    "PIE", # flake8-pie
    "T20", # flake8-print
    "PYI", # flake8-pyi
    "PT",  # flake8-pytest-style
    "Q",   # flake8-quotes
    "RSE", # flake8-raise
    "RET", # flake8-return
    "SLF", # flake8-self
    "SLOT", # flake8-slots
    "TCH", # flake8-type-checking
    "INT", # flake8-gettext
    "ERA", # eradicate
    "PD",  # pandas-vet
    "PGH", # pygrep-hooks
    "PL",  # pylint
    "TRY", # tryceratops
    "FLY", # flynt
    "NPY", # numpy
    "AIR", # airflow
    "PERF", # perflint
    "FURB", # refurb
    "LOG", # flake8-logging
    "RUF", # Ruff-specific rules
]

# 비활성화할 규칙들
lint.disable = [
    "E501",  # line too long (포맷터가 처리)
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "S101",  # assert_used (테스트에서 사용)
    "S603",  # subprocess_without_shell_equals_true (의도적인 사용)
    "S607",  # start_process_with_partial_path (의도적인 사용)
]

# 허용할 에러들
lint.ignore = [
    "E501",  # line too long
    "B008",  # do not perform function calls in argument defaults
    "C901",  # too complex
    "PLR0913", # too many arguments
    "PLR0912", # too many branches
    "PLR0915", # too many statements
    "S101",  # assert_used (테스트에서 사용)
    "S603",  # subprocess_without_shell_equals_true
    "S607",  # start_process_with_partial_path
]

# 최대 라인 길이
line-length = 88

# Import 정렬 설정 (isort 기능 통합)
lint.isort.known-first-party = [
    "demo", 
    "application", 
    "domain", 
    "infrastructure", 
    "config"
]
lint.isort.known-third-party = [
    "fastapi",
    "uvicorn", 
    "gradio",
    "langchain",
    "sentence_transformers",
    "numpy",
    "scipy",
    "scikit_learn",
    "pydantic",
    "httpx",
    "aiofiles",
    "pyyaml",
    "python_dotenv",
    "huggingface_hub",
    "pandas",
    "pillow",
    "sqlalchemy",
    "requests",
    "aiohttp",
    "tenacity",
    "dataclasses_json",
    "pydantic_settings",
    "httpx_sse",
    "rank_bm25",
]
lint.isort.sections = ["FUTURE", "STDLIB", "THIRDPARTY", "FIRSTPARTY", "LOCALFOLDER"]
lint.isort.force-single-line = false
lint.isort.force-sort-within-sections = true

# 포맷팅 설정 (black 기능 통합)
format.quote-style = "double"
format.indent-style = "space"
format.skip-magic-trailing-comma = false
format.line-ending = "auto"

# 네임스페이스 패키지 처리
namespace-packages = ["demo"]

# 미래 호환성 설정
lint.upgrade = true

# 파일별 설정
lint.per-file-ignores = [
    "__init__.py:F401",  # __init__.py에서 unused import 허용
    "tests/*:S101",      # 테스트에서 assert 허용
    "tests/*:S603",      # 테스트에서 subprocess 허용
    "tests/*:S607",      # 테스트에서 process 실행 허용
]

# 최대 복잡도
lint.mccabe.max-complexity = 10

# 보안 검사 설정 (bandit 기능 통합)
lint.security.extend-secure-cookies = []
lint.security.extend-unsafe-cookies = []
