# 한국어 RAG 처리를 위한 LangChain 템플릿

# 한국어 RAG 파이프라인
korean_rag_pipeline:
  system: "main_assistant"
  
  human_template: |
    질문: {query}
    
    검색된 문서들:
    {documents}
    
    위 문서들을 바탕으로 한국어로 답변해주세요.

# 한국어 하이브리드 RAG
korean_hybrid_rag:
  system: "main_assistant"
  
  human_template: |
    질문: {query}
    
    의미적 검색 결과:
    {semantic_results}
    
    키워드 검색 결과:
    {keyword_results}
    
    두 검색 결과를 종합하여 한국어로 답변해주세요.

# 한국어 컨텍스트 빌더
korean_context_builder:
  system: "main_assistant"
  
  human_template: |
    다음 문서들을 한국어 컨텍스트로 구성해주세요:
    
    문서들: {documents}
    
    검색 전략: {search_strategy}
    
    한국어 특화 컨텍스트 구성 규칙:
    - 관련도 높은 순으로 정렬
    - 중복 정보 제거
    - 한국어 표현으로 자연스럽게 연결