server:
  port: 8080

spring:
  application:
    name: ai-portfolio-backend
  
  # CORS 설정
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "http://127.0.0.1:5173"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# 로깅 설정
logging:
  level:
    com.aiportfolio.backend: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 환경변수 설정
app:
  gemini:
    api-key: ${GEMINI_API_KEY:}
  github:
    username: ${GITHUB_USERNAME:}
  contact:
    email: ${CONTACT_EMAIL:}
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    rate-limit:
      window: ${RATE_LIMIT_WINDOW:60000}
      max-requests: ${RATE_LIMIT_MAX_REQUESTS:100} 