server:
  port: 8080

spring:
  application:
    name: ai-portfolio-backend
  
  # PostgreSQL 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/ai_portfolio
    username: dev_user
    password: dev_password
    driver-class-name: org.postgresql.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  
  # Redis 설정
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
      database: ${REDIS_DATABASE:1}
      timeout: ${REDIS_TIMEOUT:2000}ms
      ssl:
        enabled: ${REDIS_SSL:false}
      lettuce:
        pool:
          max-active: ${REDIS_MAX_ACTIVE:8}
          max-idle: ${REDIS_MAX_IDLE:8}
          min-idle: 0
          max-wait: -1ms
        shutdown-timeout: 100ms

  # CORS 설정
  web:
    cors:
      allowed-origins: 
        - "http://localhost:3000"
        - "http://localhost:5173"
        - "http://127.0.0.1:5173"
      allowed-methods: 
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers: "*"
      allow-credentials: true

# Swagger 설정
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method

# 로깅 설정
logging:
  level:
    com.aiportfolio.backend: DEBUG
    org.springframework.web: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# 환경변수 설정
app:
  gemini:
    api-key: ${GEMINI_API_KEY:}
    model-name: gemini-2.5-flash
  github:
    username: Yamang02
  contact:
    email: ljj0210@gmail.com
  security:
    allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
    rate-limit:
      window: ${RATE_LIMIT_WINDOW:60000}
      max-requests: ${RATE_LIMIT_MAX_REQUESTS:100} 