# 청킹 전략 설정 파일
# 문서 유형별 청킹 파라미터와 전략 설정

chunking_strategies:
  
  # 프로젝트 문서 전략
  PROJECT:
    name: "프로젝트 문서 특화 청킹"
    description: "프로젝트 문서의 구조적 특성을 고려한 청킹"
    
    parameters:
      chunk_size: 600        # 프로젝트 문서는 조금 더 큰 청크
      chunk_overlap: 100     # 컨텍스트 보존을 위해 더 큰 겹침
      preserve_structure: true
      
    section_priorities:
      "프로젝트 목표": 1
      "주요 역할": 2
      "기술적 결정": 2
      "핵심 Q&A": 1
      "프로젝트 발전 과정": 3
      "Timeline": 3
      "배운 점": 4
      "summary": 1
      "skills": 1
    
    special_processing:
      qa_section: true       # Q&A 섹션을 질문-답변 쌍으로 분할
      timeline_section: true # Timeline을 연도/날짜별로 분할
      frontmatter_extraction: true # YAML frontmatter 별도 처리
      
    keywords:
      tech_patterns:
        - "Python|Java|React|Docker|Spring|FastAPI|Redis|PostgreSQL"
        - "헥사고날|아키텍처|마이크로서비스|RAG|LLM|임베딩"
        - "CI/CD|DevOps|배포|모니터링"
      
  # Q&A 문서 전략  
  QA:
    name: "Q&A 문서 특화 청킹"
    description: "질문-답변 쌍 단위로 최적화된 청킹"
    
    parameters:
      chunk_size: 800        # Q&A는 완전한 답변을 포함하기 위해 더 큰 청크
      chunk_overlap: 50      # Q&A 간 겹침은 최소화
      preserve_structure: true
      
    category_priorities:
      "architecture": 1
      "ai-services": 1
      "deployment": 2
      "development": 3
      "performance": 2
      "troubleshooting": 4
      "decisions": 3
      "learning": 4
      "frontend": 3
    
    processing_patterns:
      qa_patterns:
        - "###\\s*Q:\\s*([^#]+?)(?:\\n\\n>\\s*(.+?)(?=\\n\\n---|\\n\\n###|\\Z))"  # ### Q: ... \n\n> A: ...
        - "\\*\\*Q:\\s*([^*]+?)\\*\\*\\s*\\n\\n(?:A:\\s*)?(.+?)(?=\\n\\n\\*\\*Q:|\\n\\n---|\\Z)"  # **Q: ...** \n\nA: ...
      
      intro_extraction: true  # 문서 개요 섹션 별도 추출
      category_detection: true # 파일명/경로에서 카테고리 자동 감지
      
    keywords:
      tech_patterns:
        - "Spring Boot|FastAPI|React|Docker|Redis|PostgreSQL|Qdrant"
        - "Python|Java|TypeScript|JavaScript"
        - "API|REST|GraphQL|WebSocket"
        - "헥사고날|아키텍처|마이크로서비스"
      concept_patterns:
        - "설계|구현|개발|배포|테스트|디버깅"
        - "성능|최적화|확장성|유지보수성"
        - "보안|인증|권한"
  
  # 기본 텍스트 전략
  TEXT:
    name: "기본 텍스트 청킹"
    description: "일반 텍스트 문서용 크기 기반 청킹"
    
    parameters:
      chunk_size: 500
      chunk_overlap: 75
      preserve_structure: false
      
    processing:
      sentence_boundary: true  # 문장 경계 인식
      paragraph_boundary: true # 단락 경계 인식
      
    splitting:
      prefer_sentences: true   # 문장 단위 분할 우선
      min_chunk_size: 100     # 최소 청크 크기
      max_chunk_size: 1000    # 최대 청크 크기

# 문서 유형 감지 규칙
document_detection:
  
  # frontmatter 기반 감지
  frontmatter_patterns:
    PROJECT: 
      - "document_type:\\s*[\"']?PROJECT[\"']?"
      - "document_type:\\s*[\"']?project[\"']?"
    QA:
      - "document_type:\\s*[\"']?QA[\"']?"
      - "document_type:\\s*[\"']?qa[\"']?"
  
  # 파일 경로/이름 기반 감지
  path_patterns:
    QA:
      - "qa[_-]"     # qa_architecture.md
      - "/qa/"       # path/qa/file.md  
      - "q&a"        # q&a.md
      - "faq"        # faq.md
    PROJECT:
      - "project"
      - "portfolio"
      - "/projects/"
      - "readme\\.md$"
  
  # 내용 기반 감지 (최소 매칭 횟수)
  content_patterns:
    QA:
      patterns:
        - "###\\s*Q:"    # ### Q: 패턴
        - "\\*\\*Q:"     # **Q: 패턴  
        - "Q&A"          # Q&A 제목
        - "질문.*답변"    # 한국어 Q&A
      min_matches: 2
      
    PROJECT:
      patterns:
        - "프로젝트\\s+목표"
        - "주요\\s+역할"
        - "기술적\\s+결정"
        - "프로젝트\\s+발전\\s+과정"
        - "Timeline"
        - "기술\\s+스택"
        - "skills:\\s*\\["      # YAML skills
        - "summary:\\s*[\"']"   # YAML summary
      min_matches: 2

# 성능 튜닝 설정
performance:
  max_document_size: 1000000  # 1MB 제한
  cache_compiled_patterns: true
  parallel_processing: false  # 현재는 비활성화
  
# 디버깅 설정
debug:
  log_strategy_selection: true
  log_chunk_metadata: false
  save_analysis_results: false