# AI Portfolio Service - Demo Environment Configuration
# 데모 환경에서 사용할 설정 (로컬 모델, Mock 서비스, 메모리 기반)

# =============================================================================
# LLM Configuration (Demo)
# =============================================================================
llm:
  provider: "mock"  # 데모에서는 Mock LLM 사용
  
  # Mock LLM 설정
  mock:
    model_name: "mock-gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1000
    response_delay: 0.5
  
  # 설정 검증을 위한 더미 설정들 (사용되지 않음)
  openai:
    model_name: "gpt-3.5-turbo"
    temperature: 0.7
    max_tokens: 1000
    api_key: "demo-key"
  
  google:
    model_name: "gemini-pro"
    temperature: 0.7
    max_output_tokens: 1000
    api_key: "demo-key"

# =============================================================================
# Database Configuration (Demo - 사용 안함)
# =============================================================================
database:
  # 데모 환경에서는 사용하지 않지만 설정 검증을 위한 더미 값들
  host: "localhost"
  port: 5432
  database: "demo_db"
  username: "demo_user"
  password: "demo_password"

# =============================================================================
# Cache Configuration (Demo - 로컬 Redis)
# =============================================================================
cache:
  host: "localhost"
  port: 6379
  password: ""  # 로컬 Redis는 패스워드 없음
  database: 1  # 데모 전용 DB 번호
  key_prefix: "demo_ai_service:"
  default_ttl: 1800  # 30분 (짧은 TTL)
  context_ttl: 3600  # 1시간

# =============================================================================
# Vector Store Configuration (Demo - Memory 기반)
# =============================================================================
adapters:
  vector:
    provider: "memory"  # 데모에서는 메모리 기반 벡터 스토어
    memory:
      model_name: "sentence-transformers/all-MiniLM-L6-v2"
      similarity_threshold: 0.7
      max_results: 10
      hybrid_weight: 0.7  # Vector 검색 가중치 (0.3은 BM25)
  
  # 임베딩 어댑터 설정 (Demo - 로컬 모델)
  embedding:
    provider: "huggingface"  # 로컬 HuggingFace 모델 사용
    model_name: "sentence-transformers/all-MiniLM-L6-v2"
    batch_size: 10  # 데모에서는 작은 배치 사이즈
    normalize: true
    device: "cpu"

# =============================================================================
# Embedding Configuration (Demo)  
# =============================================================================
embedding:
  provider: "huggingface"
  model_name: "sentence-transformers/all-MiniLM-L6-v2"
  batch_size: 10
  normalize: true
  device: "cpu"

# =============================================================================
# RAG Configuration (Demo)
# =============================================================================
rag:
  chunk_size: 300  # 데모에서는 작은 청크 사이즈
  chunk_overlap: 50
  top_k: 3  # 데모에서는 적은 검색 결과
  similarity_threshold: 0.6  # 더 관대한 임계값
  max_context_length: 4000  # 짧은 컨텍스트
  project_priority_boost: true
  include_metadata: true

# =============================================================================
# Logging Configuration (Demo)
# =============================================================================
logging:
  level: "DEBUG"  # 데모에서는 상세 로그
  format: "text"  # 가독성을 위해 텍스트 형식
  include_request_id: true

# =============================================================================
# Performance Configuration (Demo)
# =============================================================================
performance:
  max_concurrent_requests: 10  # 데모에서는 낮은 동시성
  request_timeout_seconds: 15
  # db_connection_timeout: 5  # DB 사용 안함
  
  # Mock 서비스 설정
  mock_llm:
    response_delay: 0.3  # 빠른 응답을 위해 짧은 지연
    
  # 메트릭 수집 설정 (데모)
  metrics:
    collection_interval: 30  # 더 빈번한 수집
    
  # 헬스체크 설정 (데모)
  health_check:
    interval: 15  # 더 빈번한 체크
    timeout: 3

# =============================================================================
# Demo 특화 설정
# =============================================================================
demo:
  # 샘플 데이터 설정
  sample_data:
    load_on_startup: true
    documents_path: "./data/demo-documents"
    
  # UI 설정
  ui:
    show_debug_info: true
    enable_metrics_dashboard: true
    auto_refresh_interval: 5000  # 5초마다 자동 새로고침
    
  # 제한 설정
  limits:
    max_documents: 100
    max_queries_per_minute: 30
    max_response_length: 2000
